name: sampah_detector_mobile
description: A Flutter app to detect organic and inorganic waste from camera or gallery images.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  image: ^4.8.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo_app.png"
flutter_native_splash:
  color: "#F4F7F5"
  image: assets/icon/splash_logo.png
  android: true
  ios: true
  android_12:
    color: "#F4F7F5"
    image: assets/icon/splash_logo.png
